### ISSUE TITLE
Problem with 2.6.1 version under windows vista

### ISSUE THREAD

**Issue by mgian** [GillesDebunne/libQGLViewer#11]
I tried to compile my software (bulbcalculator) and also if the compilation is ok (no errors and no warnings), when I run the program I don't see the 3d view rendered with libQGLViewer.
Please note that my software is, in this regard, correct since I tired it both under Linux and under Windows 8.1 and it works well.

The system when I got the problem is:
Windows  Vista home 32 bit
Qt 5.4 with mingw 4.9.1 32 bit
libQGLViewer 2.6.1 compiled from source

on the same hardware, the program under Archlinux is working fine

Any ideas ?

**Comment by GillesDebunne** [comment]
Hello,

I suspect an OpenGl issue. Try to compile and run one of the OpenGL
examples provided by Qt and see if it works.

**Comment by mgian** [comment]
I tried to run a demo from libQGLViewer (multiView) and at least I got this error:

createContext: wglShareLists() failed. ()

and the opengl view is not shown.

I am now tring to downgrade to Qt 5.2.1 to see what happen

**Comment by GillesDebunne** [comment]
Also try to compile a basic application with a simple QGLWidget (or
QOpenGLWidget with Qt 5.4) and see how it goes.

**Comment by mgian** [comment]
I tried to compile the hellogl2 example from the Qt Distribution and i got this error:

Debugging starts
createContext: wglShareLists() failed. ()
QOpenGLShaderProgram: could not create shader program
QOpenGLShader: could not create shader
Debugging has finished


I also tried to compile the legacy hellogl example, but it also fail also if at a different point.
(I am beginning to think that the problem is with the OpenGL stack of Vista)

Hope this can help

**Comment by GillesDebunne** [comment]
Hi,

Yes, if a simple Qt / OpenGL example does not work, libQGLViewer is not
(yet) to blame. You need to fix this first, probably by investigating your
OpenGL hardware / driver situation.

Good luck.

G

**Comment by mgian** [comment]
I will. 
But I am afraid that I will need to downgrade to Qt 4.8.x series to compile for Windows Vista
Thanks

**Comment by mgian** [comment]
I confirm that using Qt 4.8.6 it compile and run correctly under Windows Vista, so the problem seems to be a compatiblity issue between Vista and Qt5 (at least on my hardware).
