### ISSUE TITLE
failed to download tarball

### ISSUE THREAD

**Issue by bricerebsamen** [GillesDebunne/libQGLViewer#12]
broken link? maybe just temporary

**Comment by GillesDebunne** [comment]
The web site changed location recently, and some files were not properly migrated.

**Comment by GillesDebunne** [comment]
Missing files were added back.

**Comment by lrineau** [comment]
It seems all files are not back. For example, http://www.libqglviewer.com/src/libQGLViewer-2.6.1.tar.gz is missing. See #15.

And the link "source repository" at http://libqglviewer.com/download.html points to http://libqglviewer.com/src/
