### ISSUE TITLE
Support for OpenGL 3.x 

### ISSUE THREAD

**Issue by JWHennessey** [GillesDebunne/libQGLViewer#14]
Hello,

Thanks for developing the library, it seems great and was very simple to
get up and running.

I'm curious if it is possible to use the library with modern OpenGL (3.x)
e.g using shaders etc? The examples I have seen use the fixed functionality
pipeline and my initial attempts to integrate VBOs aren't working.

Many thanks

**Comment by lrineau** [comment]
As far as I know, the implementation of libQGLViewer uses legacy OpenGL methods that control the [fixed function pipeline](https://www.opengl.org/wiki/Fixed_Function_Pipeline). It cannot compile in OpenGL 3.2 core profile, or in OpenGL ES 2 and later.

[GeometryFactory](http://geometryfactory.com) has hired an intern student (@maxGimeno) for six months, on porting [CGAL](http://www.cgal.org/) demos to Android (and thus to OpenGL ES). See [short job description *Porting Demo Applications to Android using Qt5*](http://geometryfactory.com/open-positions/porting-demos-to-android-using-qt5/). I am the advisor of the internship.

As all CGAL 3D demos use Qt4 and libQGLViewer, the internship has two important technical steps:
  - port the code of the demos from Qt4 to Qt5 (required to support Android),
  - try to port the code of libQGLViewer to *OpenGL 3.2 core profile* and *OpenGL ES 2* (the later is required to support Android).

@GillesDebunne has been made aware of our attempt to port libQGLViewer to OpenGL ES 2. For the moment, @maxGimeno had to disable (using macros like `#ifndef ANDROID`) big part of the libQGLViewer API. Significant part of the API (like for example the picking) cannot be ported to the modern OpenGL API, at least not in a backward-compatible way.

Maxime and I are open to discussions.

**Comment by JWHennessey** [comment]
Thanks for the response. Good to know that the libQGLViewer will be ported to QT5 soon. I'll keep an eye out for updates but for my current project I'll probably implement the essential functionality myself. Thanks.

**Comment by GillesDebunne** [comment]
Quick note: Qt5 is supported by libQGLViewer (the ANDROID case is different).

As for OpenGL 3.x, it definitively needs to be done, but it would require external contributions. In the process, a lot of the legacy code (Vec, Quaternion, Dom, ...) should be removed and the library could be simplified. @lrineau, maybe we can chat about what's done on your side?
