### ISSUE TITLE
Download link to 2.6.1 broken

### ISSUE THREAD

**Issue by bo0ts** [GillesDebunne/libQGLViewer#15]
Since the update to 2.6.2 the file http://www.libqglviewer.com/src/libQGLViewer-2.6.1.tar.gz is not available anymore breaking some automated builds.

**Comment by lrineau** [comment]
The Fedora Linux distribution has also red flags on libQGLViewer, because the upstream URL to download the sources no longer works.

**Comment by GillesDebunne** [comment]
Sorry about the inconvenience, these files got lost during the transfer of the web site to a new host.
