### ISSUE TITLE
Qt-5.5 runtime issue on msvc2013

### ISSUE THREAD

**Issue by janetournois** [GillesDebunne/libQGLViewer#17]
Hi,

because this info can be useful to other users of QGLViewer and Qt5 under Windows 8 and MSVC 2013, please let me point out the following issue.

At runtime, starting a demo that uses QGLViewer 2.6.2 or 2.6.3 with Qt-5.5.0,
on Windows 8, with MSVC 2013, needs to set the following environment variable 
QT_QPA_PLATFORM_PLUGIN_PATH=%QTDIR%\plugins\platforms\
(in my case QTDIR is "..QT-5.5.0\5.5\msvc2013_64")

Otherwise, the QApplication constructor crashes at runtime.
Hope it helps,

Jane.

**Comment by GillesDebunne** [comment]
Thanks a lot for this feedback.

Do you know if this is a documented / expected behaviour with this
platform, or if there something that we do wrong and that should be fixed
to avoid this cumbersome step?

Thanks,

Gilles

**Comment by janetournois** [comment]
Our conclusion is that some paths are hardcoded by the Qt5 installer.
So, copying an installation directory from one place to another on the same computer, or to another computer, breaks these hardcoded paths.
That's what happened to me.

The environment variable QT_QPA_PLATFORM_PLUGIN_PATH should be set only if one has such a copy-pasted installation of Qt5.

Thanks for your answer!
Jane.

**Comment by GillesDebunne** [comment]
Thanks for your update!
