### ISSUE TITLE
md5 hashes wrong for libQGLViewer-2.6.2.tar.gz and libQGLViewer-2.6.3.tar.gz

### ISSUE THREAD

**Issue by bjornpiltz** [GillesDebunne/libQGLViewer#19]
http://libqglviewer.com/src/libQGLViewer-2.6.1.tar.gz is OK, though.

Currently the webpage says:

    libQGLViewer-2.6.0.tar.gz   3.07 Mb    4534a10262c252c9fe60c6a2febe951d
    libQGLViewer-2.6.0.zip      3.74 Mb    02414f7d6bb92bd515c12e6b2f2224bb
    libQGLViewer-2.6.1.tar.gz   3.08 Mb    65d41b1fa3e1e5396cb2952b8c032c6c
    libQGLViewer-2.6.1.zip      3.74 Mb    1a1f2ba0bba268b116c43b578de10bec
    libQGLViewer-2.6.2.tar.gz   3.08 Mb    e43959c53a9e0fe5d7bb831326732cd3
    libQGLViewer-2.6.2.zip      3.74 Mb    446f000f0dcdc6aa92980ab2c300dfa9
    libQGLViewer-2.6.3.tar.gz   3.04 Mb    069f36b0a8f7cb01380a3d0bca560ace
    libQGLViewer-2.6.3.zip      3.67 Mb    41100173116f6d65015762a73a9d8112

I haven't tried the zip files.

**Comment by GillesDebunne** [comment]
The 2.6.3 were indeed incorrect and have been fixed.

Thanks for the feedback.
