### ISSUE TITLE
v 2.63 : forbidden Animation

### ISSUE THREAD

**Issue by LETARTARE** [GillesDebunne/libQGLViewer#20]
Bonjour,
tout d'abord merci beaucoup pour cette bibliothèque, j'utilise la version 2.63 avec Qt5.5 sous Vista Pro pour visualiser les chemins de l'outil sur un logiciel libre pour CNC .
Je voudrais savoir s'il est possible d’inhiber complètement l'animation par la souris ou le clavier, car il arrive souvent lors du déplacement de l'image par la souris qu'elle se mette en rotation.
Merci.

Hello,
First of all thank you very much for this library, I use the 2.63 version with Qt5.5 Vista Pro to view the paths of the tool on a free software for CNC:
I wonder if it is possible to completely inhibit the animation by mouse or keyboard, as it often happens when moving the picture with the mouse snaps into rotation.
Thank you.

![example](https://cloud.githubusercontent.com/assets/5158475/10412059/3b06fd54-6f7a-11e5-994d-bfc3bfd08532.png)
https://github.com/LETARTARE/GrblHoming

**Comment by GillesDebunne** [comment]
What you're looking for is camera's frame spinningSensitivity. Use

myViewer->camera()->frame()->setSpinningSensitivity(9e99);

to prevent this rotation animation.

**Comment by LETARTARE** [comment]
Thanks you, it's all right.
Thank you again for this very useful library.
