### ISSUE TITLE
Incorrect selection with retina display

### ISSUE THREAD

**Issue by kerautret** [GillesDebunne/libQGLViewer#22]
It looks like that the face selection on mac OSX  retina display is not correct:
The direction of convertClickToLine looks fine, but the pointUnderPixel is wrong:
 From the lib example "select.cpp" on retina display:
<img width="637" alt="selectiononretinadisplay" src="https://cloud.githubusercontent.com/assets/772865/11919991/d0cedbda-a761-11e5-98f4-3ac7f7fb1247.png">
If I just test with my second screen which is not retina it is fine:
![selectiononclassicdisplay](https://cloud.githubusercontent.com/assets/772865/11919996/f1b0714c-a761-11e5-8879-ea27bf2cf598.png)

**Comment by GillesDebunne** [comment]
This is related to 'retina' displays, and the times 2 scaling between physical and device pixels.

This is just a matter of multiplying / dividing by `devicePixelRatio` (i.e. 2) in a few places. 

Unfortunately, it is not clear which places require it in the code, except around uses of `width()` and `height()` witch are known to cause problems with a QGLWidget.

**Comment by kerautret** [comment]
Thanks for you reply,
Yes you are right, I also found this blog which mention it:
http://blog.qt.io/blog/2013/04/25/retina-display-support-for-mac-os-ios-and-x11/
If you want I can have a try if you have some idea where is the best to apply the  widget->windowHandle()->devicePixelRatio()

**Comment by GillesDebunne** [comment]
It took some time, but this issue has been fixed in the 2.9.0 version of the library.

**Comment by kerautret** [comment]
Excellent  🎉 Thanks a lo! ;)
I just see some compilation issue (see #64)
