### ISSUE TITLE
Make Failed on Odroid XU4

### ISSUE THREAD

**Issue by damanfb** [GillesDebunne/libQGLViewer#24]
I'm trying to install the library on the Odroid XU4 and I get the following output when I try to make it:

odroid@odroid:~$ cd libQGLViewer/QGLViewer/
odroid@odroid:~/libQGLViewer/QGLViewer$ qmake
odroid@odroid:~/libQGLViewer/QGLViewer$ make
g++ -c -pipe -O2 -D_REENTRANT -Wall -W -fPIC -DQT_NO_DEBUG -DQT_NO_KEYWORDS -DQT_XML_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I/usr/X11R6/include -I.moc -I. -o .obj/qglviewer.o qglviewer.cpp
In file included from /usr/include/GL/glu.h:38:0,
                 from config.h:61,
                 from domUtils.h:1,
                 from qglviewer.cpp:1:
/usr/include/GL/gl.h:134:17: error: conflicting declaration 'typedef double GLdouble'
 typedef double  GLdouble; /* double precision float */
                 ^
In file included from /usr/include/qt4/QtOpenGL/QGLWidget:1:0,
                 from config.h:55,
                 from domUtils.h:1,
                 from qglviewer.cpp:1:
/usr/include/qt4/QtOpenGL/qgl.h:85:17: note: previous declaration as 'typedef GLfloat GLdouble'
 typedef GLfloat GLdouble;
                 ^
In file included from /usr/include/GL/gl.h:2055:0,
                 from /usr/include/GL/glu.h:38,
                 from config.h:61,
                 from domUtils.h:1,
                 from qglviewer.cpp:1:
/usr/include/GL/glext.h:468:19: error: conflicting declaration 'typedef ptrdiff_t GLsizeiptr'
 typedef ptrdiff_t GLsizeiptr;
                   ^
In file included from /usr/include/qt4/QtOpenGL/qgl.h:79:0,
                 from /usr/include/qt4/QtOpenGL/QGLWidget:1,
                 from config.h:55,
                 from domUtils.h:1,
                 from qglviewer.cpp:1:
/usr/include/GLES2/gl2.h:69:25: note: previous declaration as 'typedef khronos_ssize_t GLsizeiptr'
 typedef khronos_ssize_t GLsizeiptr;
                         ^
In file included from /usr/include/GL/gl.h:2055:0,
                 from /usr/include/GL/glu.h:38,
                 from config.h:61,
                 from domUtils.h:1,
                 from qglviewer.cpp:1:
/usr/include/GL/glext.h:469:19: error: conflicting declaration 'typedef ptrdiff_t GLintptr'
 typedef ptrdiff_t GLintptr;
                   ^
In file included from /usr/include/qt4/QtOpenGL/qgl.h:79:0,
                 from /usr/include/qt4/QtOpenGL/QGLWidget:1,
                 from config.h:55,
                 from domUtils.h:1,
                 from qglviewer.cpp:1:
/usr/include/GLES2/gl2.h:70:26: note: previous declaration as 'typedef khronos_intptr_t GLintptr'
 typedef khronos_intptr_t GLintptr;
                          ^
In file included from quaternion.h:4:0,
                 from keyFrameInterpolator.h:7,
                 from camera.h:4,
                 from qglviewer.h:4,
                 from qglviewer.cpp:2:
vec.h: In member function 'qglviewer::Vec::operator const double*() const':
vec.h:153:10: error: cannot convert 'const qreal* {aka const float*}' to 'const double*' in return
   return v_;
          ^
vec.h: In member function 'qglviewer::Vec::operator double*()':
vec.h:164:10: error: cannot convert 'qreal* {aka float*}' to 'double*' in return
   return v_;
          ^
In file included from keyFrameInterpolator.h:7:0,
                 from camera.h:4,
                 from qglviewer.h:4,
                 from qglviewer.cpp:2:
quaternion.h: At global scope:
quaternion.h:110:7: error: 'void qglviewer::Quaternion::setFromRotationMatrix(const qreal (*)[3])' cannot be overloaded
  void setFromRotationMatrix(const qreal m[3][3]);
       ^
quaternion.h:107:7: error: with 'void qglviewer::Quaternion::setFromRotationMatrix(const float (*)[3])'
  void setFromRotationMatrix(const float m[3][3]);
       ^
In file included from qglviewer.h:4:0,
                 from qglviewer.cpp:2:
camera.h:346:7: error: 'void qglviewer::Camera::getProjectionMatrix(GLdouble*) const' cannot be overloaded
  void getProjectionMatrix(GLdouble m[16]) const;
       ^
camera.h:345:7: error: with 'void qglviewer::Camera::getProjectionMatrix(GLfloat*) const'
  void getProjectionMatrix(GLfloat m[16]) const;
       ^
camera.h:349:7: error: 'void qglviewer::Camera::getModelViewMatrix(GLdouble*) const' cannot be overloaded
  void getModelViewMatrix(GLdouble m[16]) const;
       ^
camera.h:348:7: error: with 'void qglviewer::Camera::getModelViewMatrix(GLfloat*) const'
  void getModelViewMatrix(GLfloat m[16]) const;
       ^
camera.h:352:7: error: 'void qglviewer::Camera::getModelViewProjectionMatrix(GLdouble*) const' cannot be overloaded
  void getModelViewProjectionMatrix(GLdouble m[16]) const;
       ^
camera.h:351:7: error: with 'void qglviewer::Camera::getModelViewProjectionMatrix(GLfloat*) const'
  void getModelViewProjectionMatrix(GLfloat m[16]) const;
       ^
Makefile:379: recipe for target '.obj/qglviewer.o' failed
make: *** [.obj/qglviewer.o] Error 1
odroid@odroid:~/libQGLViewer/QGLViewer$

**Comment by GillesDebunne** [comment]
These type errors do not seem to be specific to libQGLViewer, but rather related to your openGL gl.h header files. These do not match with Qt's typedefs, and floats and doubles are mixed up.

Chances are you will not be able to compile any of the Qt's OpenGL example with this configuration.

I mark this issue as closed for this reason. Reopen or comment if needed.
