### ISSUE TITLE
libQGLViewer-2.6.3 fails to build with g++6 (in Fedora Rawhide)

### ISSUE THREAD

**Issue by lrineau** [GillesDebunne/libQGLViewer#26]
In Fedora, the rawhide distribution is currently switching to GCC version 6. libQGLViewer fails to build with it. I have updated the libQGLViewer version to the last version (2.6.3), but it still fails to build.\

Here is the build failure log:

  https://kojipkgs.fedoraproject.org//work/tasks/874/12890874/build.log

**Comment by GillesDebunne** [comment]
Hi Laurent,

Can you confirm this problem is fixed with the latest versions, or it there still work to be done on my side ?

**Comment by lrineau** [comment]
I managed to get libQGLViewer build on Fedora rawhide. A recent version of GCC 6 seemed to have demoted the errors in VRender to simple warnings.

But I still needed to patch libQGLViewer 2.6.3 to get it build in the Fedora build system. I will push all patches to PR #30.

**Comment by GillesDebunne** [comment]
Ok thanks.

I'll try to get my hands on a Linux machine to try a clean build.
