### ISSUE TITLE
Problem with Qt 5.5.1 and QMdiSubWindow

### ISSUE THREAD

**Issue by mgian** [GillesDebunne/libQGLViewer#27]
With the 2.6.3 version, it seems that there is a problem when using a QGLViewer widget embedded in a QMdiSubWindow.

Linux Distribution Archlinux (both 32 and 64 bit)
Qt 5.5.1 (both 32 and 64 bit)

The code used is 
```
void BulbCalculator::Create3dWin() {

    this->widget3d = new QWidget();

    view3d = new Vista3D(this->widget3d);
    view3d->resize(this->widget3d->width(), this->widget3d->height());
    // Bulb 3d view window
    this->View3DWin = new QMdiSubWindow;

    View3DWin->setWidget(this->view3d);
    this->View3DWin->setWindowIcon(QIcon(QString("share/images/3d.png")));
    View3DWin->setWindowTitle(tr("3d View"));
    ui.mdiArea->addSubWindow(this->View3DWin);
}
```
which worked well at least until Qt 5.4 

The above code is in method called in the costructor of the main program class.

With Qt 5.5.1 if the QMdiSubWindow are setup as "tabbed" all work nicely, but if the subwindows are setup as MDI, then the all the subwindows become irrensponsive (or have sloppy  movements). There are no error messages or warnings. I was able to isolate the problem since if I not call the method that use the QGLViewer widget or not add (but still create) the QGLViewer widget to the subwindow, all work nicely.

It seems that QGLViewer is working well itself, since I tried a couple of examples (multiView and simpleView) and they have not any problems.

**Comment by codegrafix** [comment]
Is it possible to change easily to the new QOpenGLWidget? Are you working on that?

**Comment by GillesDebunne** [comment]
Hello,

This is a long process, and I'm not actively working on it now, for lack of
time.

Contributions are of course welcome.
