### ISSUE TITLE
Rendering the scene from a certain perspective and store rendered image in variable?

### ISSUE THREAD

**Issue by tompollok** [GillesDebunne/libQGLViewer#29]
Hey there,

is it possible to render the scene from certain perspective and then store the rendered image in a variable? The first part is explained well here: http://www.morethantechnical.com/2015/02/17/augmented-reality-on-libqglviewer-and-opencv-opengl-tips-wcode/

But my specific problem is how do i access the rendered image? Is there a way to access it, even when no "qgl viewer window" is open?

Cheers,
Tom

**Comment by GillesDebunne** [comment]
Hello,

There is a saveSnapshot() method which will save a snapshot of an image to
a file.
An option is to load this file in a QImage after that, or simply use the
grabFrameBuffer(true); method which it uses internally.

This last method requires a valid OpenGL context and would not work
offscreen, AFAIK, so I'm not sure this can be done with no qglviewer window
open.

Good luck and keep me posted.

Gilles

**Comment by tompollok** [comment]
Hello Gilles,

thank you for your help. Shortly before you answered i found also that in the saveSnapshot method there is a grabFrameBuffer method where i can get the image.

My goal is to write a multiview renderer  (stereo or n-camera setup) and create synthetic ground truth datasets for moving n-camera setups with a specified framerate. Some think similar to the Tsukuba Stereo Dataset if you have heard about it.

The current problem is that the resolution of the image i grabbed is linked to the window size of the QGLViewer. I hope i can specify the output resolution somewhere.

Cheers,
Tom

**Comment by GillesDebunne** [comment]
Hello,

The difference between grabFrameBuffer and saveSnapshot is that the later
supports 'arbitrary' output resolution. It slightly changes the camera
projection matrix and stitches several tiled images to get the result.

It might not be exactly what you need, but the source code is available for
inspiration.

Gilles
