### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by luntik2012** [GillesDebunne/libQGLViewer#31]
QtCreator. Qt5.7. msvc2015 x86 and x86_64 too
cl -c -nologo -Zc:wchar_t -FS -Zc:strictStrings -Zc:throwingNew -O2 -MD -GR -W3 -w34100 -w34189 -w44996 -w44456 -w44457 -w44458 -wd4577 -EHsc -DUNICODE -DWIN32 -DQT_NO_DEBUG -DQT_NO_KEYWORDS -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_CORE_LIB -DNDEBUG -I. -I..\..\.. -ID:\soft\Qt\5.7\msvc2015\include -ID:\soft\Qt\5.7\msvc2015\include\QtOpenGL -ID:\soft\Qt\5.7\msvc2015\include\QtWidgets -ID:\soft\Qt\5.7\msvc2015\include\QtGui -ID:\soft\Qt\5.7\msvc2015\include\QtANGLE -ID:\soft\Qt\5.7\msvc2015\include\QtXml -ID:\soft\Qt\5.7\msvc2015\include\QtCore -Irelease -I. -ID:\soft\Qt\5.7\msvc2015\mkspecs\win32-msvc2015 -Forelease\ @C:\Users\nick\AppData\Local\Temp\drawer.obj.6788.15.jom
drawer.cpp
	D:\soft\Qt\Tools\QtCreator\bin\jom.exe -f Makefile.Release
drawer.cpp(64): error C3861: 'glMultiTexCoord2f': identifier not found
drawer.cpp(65): error C3861: 'glMultiTexCoord2f': identifier not found
drawer.cpp(67): error C3861: 'glMultiTexCoord2f': identifier not found
drawer.cpp(68): error C3861: 'glMultiTexCoord2f': identifier not found
drawer.cpp(70): error C3861: 'glMultiTexCoord2f': identifier not found
drawer.cpp(71): error C3861: 'glMultiTexCoord2f': identifier not found
drawer.cpp(73): error C3861: 'glMultiTexCoord2f': identifier not found
drawer.cpp(74): error C3861: 'glMultiTexCoord2f': identifier not found
drawer.cpp(272): error C3861: 'glActiveTexture': identifier not found
drawer.cpp(275): error C3861: 'glActiveTexture': identifier not found
drawer.cpp(283): error C3861: 'glActiveTexture': identifier not found
drawer.cpp(296): error C3861: 'glActiveTexture': identifier not found
drawer.cpp(303): error C3861: 'glActiveTexture': identifier not found
drawer.cpp(316): error C3861: 'glActiveTexture': identifier not found
drawer.cpp(333): error C3861: 'glActiveTexture': identifier not found
drawer.cpp(335): error C3861: 'glActiveTexture': identifier not found
jom: D:\src\libQGLViewer\examples\contribs\dvonn\Makefile.Release [release\drawer.obj] Error 2
jom: D:\src\libQGLViewer\examples\contribs\dvonn\Makefile [release] Error 2
jom: D:\src\libQGLViewer\examples\contribs\Makefile [sub-dvonn-make_first] Error 2
jom: D:\src\libQGLViewer\Makefile [sub-examples-contribs-make_first-ordered] Error 2
15:46:15: The process "D:\soft\Qt\Tools\QtCreator\bin\jom.exe" exited with code 2.
Error while building/deploying project libQGLViewer (kit: Desktop Qt 5.7.0 MSVC2015 32bit)
When executing step "Make"

**Comment by peevesghost** [comment]
@luntik2012, have you solved this? I encounter the same problem.

**Comment by GillesDebunne** [comment]
This OpenGL style of programming is no longer supported.

I will remove the Dvonn example from the library.

In the meantime, you can simply edit `examples/contribs/contribs.pro` and remove the `dvonn.pro` line.

**Comment by luntik2012** [comment]
Thank you so. Closing it
