### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by luntik2012** [GillesDebunne/libQGLViewer#32]
# qmake
# make
ln -s libQGLViewer-qt5.so.2.6.3 libQGLViewer-qt5.so
ln -s libQGLViewer-qt5.so.2.6.3 libQGLViewer-qt5.so.2
ln -s libQGLViewer-qt5.so.2.6.3 libQGLViewer-qt5.so.2.6
make[1]: Leaving directory '/tmp/libQGLViewer/QGLViewer'
cd examples/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /tmp/libQGLViewer/examples/examples.pro -o Makefile ) && make -f Makefile 
make[1]: Entering directory '/tmp/libQGLViewer/examples'
cd animation/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /tmp/libQGLViewer/examples/animation/animation.pro -o Makefile ) && make -f Makefile 
make[2]: Entering directory '/tmp/libQGLViewer/examples/animation'
g++ -c -m64 -pipe -O2 -D_REENTRANT -Wall -W -fPIC -DQT_NO_DEBUG -DQT_NO_KEYWORDS -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -I../.. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtOpenGL -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I.moc -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o .obj/animation.o animation.cpp
g++ -c -m64 -pipe -O2 -D_REENTRANT -Wall -W -fPIC -DQT_NO_DEBUG -DQT_NO_KEYWORDS -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -I../.. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtOpenGL -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I.moc -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o .obj/main.o main.cpp
g++ -m64 -Wl,-O1 -Wl,-rpath,/tmp/libQGLViewer/QGLViewer -o animation .obj/animation.o .obj/main.o   -L/usr/X11R6/lib64 -L../../QGLViewer -lQGLViewer -lGL -lQt5OpenGL -lQt5Widgets -lQt5Gui -lQt5Xml -lQt5Core -lpthread 
/usr/bin/ld: cannot find -lQGLViewer
collect2: error: ld returned 1 exit status
Makefile:86: recipe for target 'animation' failed
make[2]: *** [animation] Error 1
make[2]: Leaving directory '/tmp/libQGLViewer/examples/animation'
Makefile:65: recipe for target 'sub-animation-make_first' failed
make[1]: *** [sub-animation-make_first] Error 2
make[1]: Leaving directory '/tmp/libQGLViewer/examples'
Makefile:88: recipe for target 'sub-examples-make_first-ordered' failed
make: *** [sub-examples-make_first-ordered] Error 2

**Comment by lrineau** [comment]
@GillesDebunne This issue is related to the issue #18, that was solved by the commit cb757cd. That commit was incomplete, because the `examples.pri` should be changed as well, and probably also `designerPlugin/designerPlugin.pro`.

**Comment by GillesDebunne** [comment]
This is a blind fix, I dot own a Linux machine to test this.
