### ISSUE TITLE
setBackgroundColor assert crash

### ISSUE THREAD

**Issue by luntik2012** [GillesDebunne/libQGLViewer#33]
```

QColor c(Qt::red);

viewer->setBackgroundColor(c);

```
ASSERT: "false" in file qgl.cpp, line 128

**Comment by GillesDebunne** [comment]
Thanks for this feedback.

`setBackgroundColor(color)` simply calls `qglClearColor(color)`. This
crash hence seems to be Qt-related. You can confirm this by
instantiating a plain QGLWidget and calling `qglClearColor(Qt::red)`.
This should crash too, and you may want to check your OpenGl
configuration.


On Mon, Sep 19, 2016 at 12:12 PM, Nikita Kostovsky <notifications@github.com

**Comment by luntik2012** [comment]
I had this issue on win7, now I've tested it on linux. I think you cannot just call QGLWidget::qglClearColor(QColor(Qt::red));

So there is my code:
```
// mainwindow.h
#pragma once

#include <QMainWindow>
#include <QGL>

class MainWindow : public QMainWindow
{
    Q_OBJECT

public:
    explicit MainWindow(QWidget *parent = 0);
    ~MainWindow();

private:
    QGLWidget *m_viewer;
};
```

**Comment by GillesDebunne** [comment]
Thanks a lot for this feedback.

I'll close this since it is not a QGLViewer specific issue.

I wonder if this could be a problem with your configuration, since I could not find other similar issues reported on the web.
