### ISSUE TITLE
libqglviewer 2.6.4 build failure due to packaging bug

### ISSUE THREAD

**Issue by ilovezfs** [GillesDebunne/libQGLViewer#34]
If I build from this repository by checking out the 2.6.4 tag, there's no problem. However, using the release tarball (http://www.libqglviewer.com/src/libQGLViewer-2.6.4.tar.gz), the build fails with the following error:
```
==> qmake PREFIX=/usr/local/Cellar/libqglviewer/2.6.4 DOC_DIR=/usr/local/Cellar/libqglviewer/2.6.4/share/doc/libqglviewer
==> make install
make: *** No rule to make target `qglviewer_fr.qm', needed by `QGLViewer.framework/Versions/2/Headers/qglviewer_fr.qm'.  Stop.
```

**Comment by GillesDebunne** [comment]
There was a packaging problem weirdly related to an XCode update.
This should be fixed now (re-download the file, same file name)
Thanks for this feedback.

**Comment by ilovezfs** [comment]
@GillesDebunne thanks!
