### ISSUE TITLE
Can i use shader in libQGLViewer?

### ISSUE THREAD

**Issue by stoneszone** [GillesDebunne/libQGLViewer#35]
Hello,

Can I use shader with libQGLViewer? I can not find any examples related to this. Thanks!

**Comment by GillesDebunne** [comment]
It is technically possible, but this library was made before shaders got popular and there is no example demonstrating their use.

One would need to switch to `QOpenGLWidget` and change the `draw` methods to use shaders, importing the camera parameters into them.
