### ISSUE TITLE
sharewidget warning

### ISSUE THREAD

**Issue by tompollok** [GillesDebunne/libQGLViewer#39]
I get a warning for when i create an object from my derived QGLViewer

The constructor with a QGLFormat is deprecated, use the regular contructor instead.

class DerivedViewer : public QGLViewer
{
public:
   DerivedViewer()
  {
   //nothing
  }

}

DerivedViewer* viewer = new DerivedViewer();

QGLViewer::QGLViewer(const QGLFormat &format, QWidget *parent,
                     const QGLWidget *shareWidget, Qt::WindowFlags flags)
    : QOpenGLWidget(parent, flags) {
  Q_UNUSED(format);
  Q_UNUSED(shareWidget);
  qWarning("The constructor with a QGLFormat is deprecated, use the regular "
           "contructor instead.");
  defaultConstructor();
}

What am i supposed to not get the warning?

**Comment by GillesDebunne** [comment]
Hi,

This message was added after the switch to `QOpenGLWidget` in version 2.7.0.

The constructor with no parameters you create should not call this method, it should call 
```
QGLViewer(QWidget *parent = 0, const QGLWidget *shareWidget, Qt::WindowFlags flags)
```
instead.

Can you make sure there is no version mismatch between your headers and the library. Did you update both, and recompile everything from scratch. That would be my guess here.

**Comment by GillesDebunne** [comment]
Closing. Please reopen if this is still an issue.

**Comment by GillesDebunne** [comment]
You are absolutely right, there is a mismatch with the new `QOpenGLWidget` and the deprecated ones kept for backward compatibility.

A new 2.7.1 release should fix the problem. Feel free to comment if there is still an issue
