### ISSUE TITLE
Problems during compilation

### ISSUE THREAD

**Issue by devds** [GillesDebunne/libQGLViewer#41]
I am compiling under Qt5.9.2 and mingw  .
QGLViewer compils without error but designerPlugin project   gets error as from attached screenshoot.
Any help?
![img](https://user-images.githubusercontent.com/4224920/32264853-ecdab450-bee0-11e7-8233-14c1e6ca67f2.png)

**Comment by GillesDebunne** [comment]
The options `-L../QGLViewer -lQGLViewer2` state that we are looking for a file named `libQGLViewer2.lib` in the `QGLViewer` directory.

Can you check that this file exists ? It should have been created as a result of the compilation in the `QGLViewer` directory.

Workaround: if you're not planning to use the designer plugin, you can simply remove `designerPlugin` from the `SUBDIRS` in `libQGLViewer.pro` and run `make` again

**Comment by devds** [comment]
ok.
Just to know: what does "designerPlugin" needs for? What's its aim?

**Comment by devds** [comment]
I removed "designerPlugin" from SUBDIRS.
Still getting errors : "cannot find lQGLViewer2
P.S. I checked about libQGLViewer2.lib : It doesn't exist.
I have found libQGLViewer2.a in QGLViewer.
How can solve?

**Comment by GillesDebunne** [comment]
> Still getting errors : "cannot find lQGLViewer2

When are you getting these errors? When building the examples? Can you share a log? 

> I have found libQGLViewer2.a in QGLViewer.
My bad `.lib` is created by windows compilers. This `.a`is the actual library. This is a *static* library, not the dynamic library (`.so`) that should have been created by default. Did you specify the `QGLVIEWER_STATIC` option when you ran `qmake`?

To start on a clean plate, please run `make clean; qmake; make` and share the log.

**Comment by GillesDebunne** [comment]
No feedback, closing.
