### ISSUE TITLE
Please reopen the issue about the deprecated ctor

### ISSUE THREAD

**Issue by CDitzel** [GillesDebunne/libQGLViewer#42]
Im sorry, I dont get your explanation int hat very issue. Even the accompanying examples (thetextureViewer, etc. ) prompt the warning that the contructor is deprecated. I subclassed QGLViewer in this fashion

ViewerWidget::ViewerWidget(QString const& path, QWidget* parent) : QGLViewer{ parent } , pathimage_{ path }
{}`

and get the infamous warning, what am I supposed to to here, or rather, what do I have to pass as a sharedWidget argument in order to satisfy the Qused Macro? Both header and source file are of the latest version.

**Comment by GillesDebunne** [comment]
Reopening #39
