### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by bjornpiltz** [GillesDebunne/libQGLViewer#47]
How about making a minor release? It's been two years, and the [missing include in camera.h](https://github.com/GillesDebunne/libQGLViewer/commit/eadcffc97dad818b59ce72d4d22c000b9db0df34) prevents QGLViewer from working out of the box.

**Comment by GillesDebunne** [comment]
You're absolutely right. The code on GitHub was up to date and had the fix,
but I didn't realize I forgot to create a new version out of it. Just did.
Thanks

Gilles
