### ISSUE TITLE
How to change the size and shape of displayed point?

### ISSUE THREAD

**Issue by Micalson** [GillesDebunne/libQGLViewer#48]
Hello, thank you for your nice code. I am new to it. I have two questions:
1) How could I change the shape of displayed point? 
2) How to display the normal of the point?
Thank you for you reply.

Regards,

**Comment by GillesDebunne** [comment]
Hello,
Your question is a bit vague. However, this seems to be related to OpenGL display of points, and not specific to libQGLViewer, which is simply a wrapper to create a scene viewer. I advise you to look at the numerous OpenGL tutorials on this subject, which can be ported in QGLViewer's `draw()` method.
