### ISSUE TITLE
How to rotate the model at the identical step?

### ISSUE THREAD

**Issue by tub-sgg** [GillesDebunne/libQGLViewer#50]
I want to create two windows, in one window it will show half part  of the model while another display the whole model.Now, I want to rotate the model in one window and the other will move at the same step and same observing view? Any hints? Thanks  a lot

**Comment by GillesDebunne** [comment]
You need to synchronize the camera positions / orientations in the two
viewers.

Using listeners, detect when a camera is changed and duplicate the values
in the other viewer.

**Comment by GillesDebunne** [comment]
Closing this issue
