### ISSUE TITLE
Problem Installing on MACOS 12

### ISSUE THREAD

**Issue by shersoni610** [GillesDebunne/libQGLViewer#57]
Hello,

I am facing problems in installing the lib on the MAC running the latest OS version 12.
I could not find QOpenGLWidget in the Qt library. Any suggestion is welcome.

**Comment by GillesDebunne** [comment]
Hello,

You are probably using Qt6, which was not supported by the library
officially until today and the release of version 2.8.0.

Gilles

**Comment by GillesDebunne** [comment]
Closing this issue
