### ISSUE TITLE
SSAO rendering

### ISSUE THREAD

**Issue by yvanblanchard** [GillesDebunne/libQGLViewer#59]
Hello,
Do you have any plans to integrate SSAO (Ambiant Occlusion, with Light shadows), rendering in the lib?
Thank you

**Comment by GillesDebunne** [comment]
Hello,

There is no such plan. The library is aimed at displaying scenes, the
rendering part is independent.

**Comment by yvanblanchard** [comment]
OK, thank you Gilles.

https://github.com/diharaw/sdf-baking
https://github.com/LiangliangNan/Easy3D
