### ISSUE TITLE
Toggle grid display and resize by code 

### ISSUE THREAD

**Issue by yvanblanchard** [GillesDebunne/libQGLViewer#60]
Hello,

do you know how to toggle on/off display of the Grid (by default, done by key "G"). And also, How to change the grid settings (number of lines, width, etc).

thank you.

**Comment by GillesDebunne** [comment]
Hello and sorry for the late response.

There are `toggleGridIsDrawn()` and `setGridIsDrawn` methods in `qglviewer.h` to do that.

There is no way to customise the drawing of the grid, but the code can easily be duplicated and customised as needed.
