### ISSUE TITLE
CMake integration.

### ISSUE THREAD

**Issue by fghoussen** [GillesDebunne/libQGLViewer#61]
Great tool: would be nice to have cmake integration.

**Comment by fghoussen** [comment]
Tried cmake integration here https://github.com/fghoussen/libQGLViewer/tree/cmake but doesn't work https://github.com/fghoussen/libQGLViewer/actions/runs/3642962449/jobs/6150661837.

Don't know enough the repo to get this done. But I can PR that as a start if this sound good to you :)

**Comment by fghoussen** [comment]
got it to work: checkout #62

**Comment by GillesDebunne** [comment]
Thanks a lot for this contribution.
