### ISSUE TITLE
Mixing 2D and 3D viewer?

### ISSUE THREAD

**Issue by fghoussen** [GillesDebunne/libQGLViewer#68]
Does `libQGLViewer` allow to mix 2D and 3D viewer?

For instance, it is possible to display a 2D image (jpg) in 1 of the 4 quadrant of the multi viewer example: https://libqglviewer.com/examples/multiView.html? If so, is there already an example? If not, are there possible workaround?

Franck

Note: this is more a question than an issue but not sure where to ask it.

**Comment by kerautret** [comment]
Hi fghoussen, 
Not sure that you question is directly related to QglViewer itself, but perhaps it can help you can have a look to the tools [sliceViewer](https://dgtal-team.github.io/doctools-nightly/sliceViewer.html) of  [DGtalTools](https://github.com/DGtal-team/DGtalTools) projet potentially you can, you can find some examples with the source code. Here is an preview: 
![8678ca02-6add-11e5-9d83-fbcf3608612f](https://user-images.githubusercontent.com/772865/227159097-3f408ffd-32c3-4580-a538-c9f416322d11.png)
If your question is more related to display images in the viewer itself, you have here also an exemple of Image display inside the 3D with the tools [3dImageViewer](https://dgtal-team.github.io/doctools-nightly/Doc3dImageViewer.html)
Hope it helps you ;)

**Comment by fghoussen** [comment]
Indeed, didn't know https://github.com/DGtal-team/DGtalTools: I'll have a look! Thanks :)

**Comment by GillesDebunne** [comment]
You can layout 2D and 3D widgets with Qt. If the 2D view is a 'flat' view of your 3d scene, consider using an orthographic camera.
